# Generated by Django 2.1.4 on 2018-12-08 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2018, 12, 9), verbose_name='date_published'),
        ),
    ]
